Dept 1
lsanchezcode/shoutout_frontend pull request #2
Opened 2022-11-04 19:23 UTC by agonxalez

2022-11-04 19:35 UTC, blamboy090 commented
Looks good! Only thing which may be addressed in a new card but once the logout is removed the last shoutout will touch the bottom of the screen do we want to preemptively add some padding to the bottom of the screen?

2022-11-04 19:44 UTC, blamboy090 commented
LGTM - Resize works nicely at 49vw, good work!

2022-11-04 21:12 UTC, nkhorvash commented
This looks really nice! I have a few comments, but they're pretty nit-picky.

Kathleen mentioned using channel.name instead of channel.id.

Other than that, there's a few minor places the site could be closer to Figma. For some of them I was told to make changes for similar things, so I'm mentioning them here.

There is extra space between the top of the shoutout card and the first line of text.
There is not enough space at the top of the page (above the logo).

Check with PO about the title size responding before we merge this (I like it, but since the AC doesn't specify, it's a cya)
also, the max font size for the keeping... h1, it gets up to 52, while it's 48 in Figma and font weight is 350 (300 in Figma)

In chrome dev tools, when I set the screen dimensions to iphone SE, there is a tiny bit less space on the right than the left, because it has stopped adjusting size. It's VERY slight.

2022-11-04 21:36 UTC, bdurel requested changes
Hey Alberto, I focused on changes to meet team naming standards and have a question about duplication of types and interfaces. Also agree with Naysan's take on styling. I might have something to add regarding matching styling.

2022-11-04 21:36 UTC, bdurel commented on components/shoutouts-temp/Shoutouts.module.css
> +@font-face {
This a note for the whole branch, not this particular line. Going forward, please name branches in kebab-case, since that's our team standard. 'dept-1-most-recent-shoutouts ' is easier to read and more descriptive.

2022-11-04 21:36 UTC, bdurel commented on components/shoutouts-temp/__test__/shoutoutcomp.test.tsx
> +import { render, screen } from '@testing-library/react';
rename as 'shoutouts-comp.test.tsx' to be consistant with the name of the component as well as our standard style of all kebab-case

2022-11-04 21:36 UTC, bdurel commented on components/shoutouts-temp/__test__/mockShoutout.json
> +{
rename as 'mock-shoutout.json' to be consistant with team standards

2022-11-04 21:36 UTC, bdurel commented on components/shoutouts-temp/Shoutouts.module.scss
> +@font-face {
our team standard is to name all possible files in lower-kebab-case, so this would be 'shoutouts.module.scss'

2022-11-04 21:36 UTC, bdurel commented on ts/interfaces.ts
> +export interface Shoutout {
I'm unclear about whether these should be types or interfaces. Devon created these as types already, which makes sense to me. Perhaps it makes more sense for some to be types and other be interfaces, but as it is duplicating the same types in an interface file is not DRY and could get confusing.

2022-11-04 21:36 UTC, bdurel commented on components/shoutouts-temp/shoutouts-comp.tsx
> +import Link from 'next/link';
remove unused import

2022-11-04 21:36 UTC, bdurel commented on components/shoutouts-temp/shoutouts-comp.tsx
> +        <span className={styles.subtext}>{`#${shoutout.channel?.id}`}</span>
Brent mentioned using semantic tags, preferably custom ones. I'm not sure if we can do custom ones in ts/nextjs. Haven't tried yet, but I will when I dive into the profile page. In any event this doesn't need to be changed to pass a PR right now, but I think worth mentioning.

2022-11-04 22:06 UTC, bdurel commented on components/shoutouts-temp/Shoutouts.module.scss
> +  border-radius: 1rem;
Brent said that we should be using em unless we need to reset em to the root. In most cases we should have ems instead of rems. We'll need to change these as we paste in styling from team 2, as we almost exlcusively used rems.

2022-11-04 22:41 UTC, nkhorvash commented
All the visual things I mentioned are spot on now.

2022-11-07 16:57 UTC, bdurel requested changes
1. Looks to me like there is more space at the top of the of the figma prototype (left side in attached image) has more space between the icon and the top of the page. 
2. Otherwise, the spacing looks spot on to me.
3. Can you put the pictures folder and fonts folder inside another folder in the root directory called assets? I left a note in slack this morning about organizing assets that way.
4. Make the naming of the shoutout component and testing consistent
5.  That's it for me. Might need to get someone besides Naysan to review though. Devon and him are out today.


![Screenshot 2022-11-07 114258](https://user-images.githubusercontent.com/114426964/200366009-8c407873-367b-4116-a2c8-cb76c0019473.png)

2022-11-07 16:57 UTC, bdurel commented on components/shoutouts-temp/shoutouts-comp.tsx
> +const ShoutoutComp = (props: { shoutout: Shoutout }, key: number) => {
change ShoutoutComp to ShoutoutsComp to be consistant with file name.

2022-11-07 16:57 UTC, bdurel commented on components/shoutouts-temp/__test__/shoutout-comp.test.tsx
> +import { render, screen } from '@testing-library/react';
Rename this file to be consistant with the component's name or rename the other ones, so that testing, component and names are either "shoutout" or shoutouts." It gets confusing with the name changes.

2022-11-07 19:43 UTC, blamboy090 commented
Looks good sir, excellent work

2022-11-08 18:14 UTC, bdurel approved these changes

2022-11-08 18:17 UTC, merged