Dept 13 logout button on every page
lsanchezcode/shoutout_frontend pull request #22
Opened 2022-11-18 19:31 UTC by blamboy090

Created Layout for application
Log out button persists on each page

2022-11-18 20:15 UTC, agonxalez requested changes

2022-11-18 20:15 UTC, agonxalez commented on pages/_app.tsx
> +import styles from '@/styles/Home.module.css';
Take this out and WE CALL IT GOOOOOOOOOOOOOOOOOOD

2022-11-18 20:31 UTC, blamboy090 commented on pages/_app.tsx
> +import styles from '@/styles/Home.module.css';
Updated!

2022-11-18 20:31 UTC, agonxalez approved these changes
lgtm

2022-11-21 17:40 UTC, bdurel approved these changes
Nice work Ben. This all looks good to me.

2022-11-21 17:43 UTC, merged