Dept 40 shoutout icons
lsanchezcode/shoutout_frontend pull request #25
Opened 2022-11-22 00:17 UTC by nkhorvash

This card adds user icons to shoutout cards

A bug fix card will be added to the backlog for the small gap between the image and its border on some avatars.

A tech debt card will be added for testing as well.

A card will also be added to make the number of avatars displayed responsive to the width of the card, per conversation with Kathleen Gorman.

2022-11-22 01:10 UTC, bdurel requested changes
Hey Naysan, nice work. I have a few housekeeping notes - mostly just cleaning up the scss file. Also looking for some clarification. I believe that we decided to reverse the order of the icon stack so that it is in the order that you have it, and not the way it is on the figma (with the last avatar on top). Is that correct? I see a note suggesting it on Devlon's spike, but I don't see it mentioned elsewhere. Besides the scss notes, it looks good to me. As an aside, I know that you have a border that matches the figma, but I think it would look better with a thicker border (that actually looks like the figma)? Maybe 3 or 4 pixels? What do you think?

2022-11-22 16:12 UTC, nkhorvash commented on components/shoutouts-temp/shoutouts-comp.tsx
> +                  '& .MuiAvatar-img': { width: '32px', height: '32px' },
I can make it rems, but it's bigger than the container to try to fill the gap (which appeared to work partially, but not completely.

2022-11-22 16:53 UTC, nkhorvash commented on components/shoutouts-temp/shoutouts-comp.tsx
> +                  '& .MuiAvatar-img': { width: '32px', height: '32px' },
Actually, that was true, but I changed it for something a little better. Not sure how it happened, but this is missing a few changes that should be in there. I'm fixing it now.

2022-11-22 17:18 UTC, nkhorvash commented
There was a lot of cleanup to do, and a few bits of code that I thought were saved somehow were not in the project (like box-sizing). Now things look right to me, but please take another look.

I've also added a note to the card in JIRA to clarify the icon order, I was operating based on Devon's spike, but neglected to call out  that deviation from figma in my AC, good catch.

2022-11-22 17:39 UTC, bdurel approved these changes
Thanks for cleaning it up. Looks great and opperates as it should apart from the avatar bug. Has my approval. Well done! Also, if you're interested, I added the bug fix card to the backlog. My current suspicion is that borders aren't meant to be used with MUI's avatar, but who knows?

2022-11-22 17:49 UTC, Incarnate-Infinity commented
@nkhorvash Largely looking good, just have a couple of thoughts.

Firstly, is 8 avatars and the "extra avatars" badge as a 9th the intended number of icons we want to have, or was the intention to have 10 total? Either way is fine, I just wanted to check and be sure. I can't recall if we had decided on an amount and 9 just feels odd to me somehow.

> Thanks for cleaning it up. Looks great and opperates as it should apart from the avatar bug. Has my approval. Well done! Also, if you're interested, I added the bug fix card to the backlog. My current suspicion is that borders aren't meant to be used with MUI's avatar, but who knows?

Secondly is in reference to @bdurel 's comment quoted above. I think the culprit may not be MUI's profile icon component but in fact the nextjs Image component. I only used the profile icon component a bit in the sandbox for the research spike on this but I don't believe I had the issue with the border gap, however I vividly recall dealing with that issue even with the custom-built icon component I made for DEPT1's version of the project, which did not use MUI's component but did use nextjs's Image component.

I could be wrong there, but I figured the information might be worth having. Once the first point is answered I think this'll be good to go!

2022-11-22 18:00 UTC, nkhorvash commented
@Incarnate-Infinity I spoke with Kathleen about your question, and basically that is the max that will fit on a card at our smallest supported screen size. I will add a card today to make the visible icons responsive to screen size.

Also, excellent point about the bug! I added a comment to the bug card, Devon if you want to add to or amend that, please do.

2022-11-22 18:03 UTC, Incarnate-Infinity approved these changes
@nkhorvash That all makes sense, I just wanted to be sure on that!

LGTM 👍

2022-11-30 15:59 UTC, Incarnate-Infinity commented
LGTM 👍

2022-11-30 17:16 UTC, merged