Dept 9 login logout
lsanchezcode/shoutout_frontend pull request #3
Opened 2022-11-07 16:52 UTC by blamboy090

2022-11-07 17:30 UTC, bdurel requested changes
Looks good Ben. I do have a few comments to clear up before merging. In addition to what I noted in the code:
1. Going forward please name branches along the lines of what Devon added to our team standards (kebab-case).
2. I think it's important to settle on where pictures and fonts are going to go in the file structure. In slack this morning, I suggested a new folder called assets in the root directory that could house fonts and pictures. Alberto's branch was going to put pictures in the root folder. The project could get difficult to navigate if we're duplicating folders in different places.

2022-11-07 17:30 UTC, bdurel commented on components/logout/logout.module.css
> +    padding: 0.75rem 2.5rem;
My understanding from the meeting with Brent was that we're switching to ems unless a root reset becomes required due to styling that changes em to be different from rem. I don't know if rems are required here, but in my brief experience since the meeting with Brent, it seems like rems aren't necessaary very often. I might be mistaken about all this though. Alberto and I are waiting for Kathleen's input on the matter.

2022-11-07 17:30 UTC, bdurel commented on components/logout/logout.module.css
> +    border-radius: 8px;
Are pixels necessary here? Could we use ems instead?

2022-11-07 17:30 UTC, bdurel commented on components/login/login.module.css
> +.loginContainer {
I have the same questions here as I had for the logout css module.

2022-11-07 17:30 UTC, bdurel commented on components/logout/__test__/logout.test.tsx
> +})
add additional line at the end of each file

2022-11-07 17:30 UTC, bdurel commented on components/logout/__test__/logout.test.tsx
> +describe("Logout Component", () => {
Change prettier setting from double to single quote. We decided to use single quotes as the team standard.

2022-11-07 17:39 UTC, blamboy090 commented on components/logout/logout.module.css
> +    border-radius: 8px;
Changed to ems

2022-11-07 17:39 UTC, blamboy090 commented on components/login/login.module.css
> +.loginContainer {
Changed to ems

2022-11-07 17:40 UTC, blamboy090 commented on components/logout/__test__/logout.test.tsx
> +})
added

2022-11-07 17:46 UTC, blamboy090 commented on components/logout/__test__/logout.test.tsx
> +describe("Logout Component", () => {
changed to single quote, linted

2022-11-11 16:57 UTC, nkhorvash approved these changes
LGTM

2022-11-11 17:04 UTC, merged