Dept 71 search query
lsanchezcode/shoutout_frontend pull request #43
Opened 2022-12-06 22:33 UTC by agonxalez

2022-12-08 16:16 UTC, bdurel requested changes
Apart from removing the console.log, the code looks good. Functionally I have a couple of questions, but I'm not clear on whether these issues have to do with your card. (1) I am wondering about something that's happening when the search results load. Briefly the "Your search does not match any profiles." error flashes before search results are shown. This happens both when making the initial search and when navigating back from a user profile. I believe fixing that might be outside the scope of your card though. (2) This one might be more within the scope, since search results not appearing is mentioned in Jira. When I make a search for "a" from the search results page, then click on a see shoutouts for a user, and then click the back I get no search results like this...
![image](https://user-images.githubusercontent.com/114426964/206504976-08eb6073-8145-47b4-b59f-0ee4c801aed8.png)

2022-12-08 16:16 UTC, bdurel commented on components/search/index.tsx
> +  console.log(currentPage);
remove console.log

2022-12-08 19:19 UTC, bdurel commented
Good work on fixing that back/disappearing search results bugginess. It all looks good apart from the flashing error message. Is that going to be on a separate bugfix card? If so, this passes for me.

2022-12-08 19:23 UTC, bdurel commented
Flashing is a separate issue from this card, so this passes.

2022-12-08 19:23 UTC, bdurel approved these changes

2022-12-09 21:02 UTC, lsanchezcode approved these changes
LGTM :)

2022-12-12 16:51 UTC, merged