Dept 30 add home button to navigation
lsanchezcode/shoutout_frontend pull request #46
Opened 2022-12-09 19:16 UTC by blamboy090

Updated styling for log out 
Added home navigational element with styling
While on home page button is highlighted

2022-12-12 19:10 UTC, lsanchezcode commented on components/dept-heading/dept-heading.module.scss
> +
Maybe get rid of the extra space?

2022-12-12 21:38 UTC, blamboy090 commented on components/dept-heading/dept-heading.module.scss
> +
Updated!

2022-12-13 00:20 UTC, nkhorvash requested changes
I'm glad to get the home button on the site, it helps a lot! The appearance is nice and it's keyboard navigable! One weird thing, line 35 of search-result/index.tsx has a console.log of the search results. This is not in sprint-2, but it doesn't show up in your diff??? Not sure how that works (yay git), but I don't think we want that in there.

2022-12-13 00:20 UTC, nkhorvash commented on components/logout/logout.module.scss
> +  margin-left: 25px;
shouldn't this be in em?

2022-12-13 00:20 UTC, nkhorvash commented on components/home-button/home-button.module.scss
> +  font-size: 1em;
Figma phase 3 says 14px font size (slightly less then 1em). Just wondering if that's a change Kathleen approved.

2022-12-13 15:10 UTC, blamboy090 commented on components/logout/logout.module.scss
> +  margin-left: 25px;
updated

2022-12-13 15:12 UTC, blamboy090 commented on components/home-button/home-button.module.scss
> +  font-size: 1em;
updated

2022-12-13 16:57 UTC, nkhorvash approved these changes
Everything looks good. The console.log is gone now, maybe the last time you pulled sprint-2 it was removed, or there was something weird in my local. Either way, looks good.

2022-12-13 17:03 UTC, merged