Dept 73 dashboard
lsanchezcode/shoutout_frontend pull request #53
Opened 2022-12-14 20:07 UTC by agonxalez

2022-12-14 21:20 UTC, blamboy090 approved these changes
Excellent work! I did not see mobile styling as part of your AC so I am going to suggest we create a card in the backlog for that, otherwise LGTM!

2022-12-15 15:18 UTC, bdurel requested changes
Hey Alberto, nice work. I've got some small questions to clear up in my comments regarding types and naming. I'm also wondering about Ben's mobile comment. I know that it doesn't mention mobile in the AC, but I was under the impression that mobile was implied unless otherwise stated. But maybe I'm incorrect here. Either way, it would be helpful to clear up. This might not be relevent if mobile/responsiveness is broken out into another card. It's also a very small thing, but on resize at around 50%, there's some bouncy behavior that I noticed when changing the year in the dropdown:
![image](https://user-images.githubusercontent.com/114426964/207897141-ab6c4159-1d35-4044-b975-5fd50c1d91ac.png)
![image](https://user-images.githubusercontent.com/114426964/207897245-16dd588a-1857-4ac8-88c8-95ce28d030f4.png)

2022-12-15 15:18 UTC, bdurel commented on components/dashboard/dropdown.tsx
> +    option: (provided: any, state: { isSelected: any }) => ({
Wondering why these have an any type? Is there no way to be more specific?

2022-12-15 15:18 UTC, bdurel commented on ts/types.ts
> +  onChange: any;
Wondering why theis has an any type? Is there no way to be more specific?

2022-12-15 19:24 UTC, bdurel requested changes

2022-12-15 19:24 UTC, bdurel commented on components/dashboard/index.tsx
>  import styles from './dashboardcomp.module.scss';
I know this gets a bit confusing, but the components are now being named after the folder name. So this one should be dashboard.tsx as in components/dashboard/dashboard.tsx. Note: only using index for pages, so the index.tsx in pages/dashboard/index.tsx is correct as you currently have it.

2022-12-15 19:24 UTC, bdurel commented on components/dashboard/dashboardcomp.module.scss
> -.header {
When you change components/dashboard/index.tsx to components/dashboard/dashboard.tsx, this file should be changed to dashboard.module.tsx.

2022-12-15 20:03 UTC, bdurel approved these changes

2022-12-15 20:03 UTC, bdurel commented
LGTM!

2022-12-15 20:16 UTC, merged