Dept 100 add user icons to search results
lsanchezcode/shoutout_frontend pull request #63
Opened 2023-01-04 17:29 UTC by blamboy090

2023-01-04 18:46 UTC, bdurel requested changes
Looks good Ben. Indistinguishable from the figma. I do have a question about the use of avatar group. Might make more sense to wrap the avatar and p tags in a div or section tag.

2023-01-04 18:46 UTC, bdurel commented on components/search-result/search-result-box.tsx
> +      <AvatarGroup
I'm a little confused by the use of avatar group. Since the search results only include a a single avatar, I don't think an avatar group is needed.

2023-01-04 18:53 UTC, bdurel approved these changes

2023-01-04 19:03 UTC, blamboy090 commented on components/search-result/search-result-box.tsx
> +      <AvatarGroup
Honestly I couldnt get the profile icons to the appropriate size with out the avatar group, I will reach out to Kathleen and see if a refactor is necessary

2023-01-04 21:09 UTC, blamboy090 commented on components/search-result/search-result-box.tsx
> +      <AvatarGroup
Updated: Please advise with new newly implemented changes the "see profile" button does collapse at resolution sizes smaller than 580px width. As discussed with Kathleen at that size we will be switching to a mobile view so the collapse will not be addressed here

2023-01-05 14:42 UTC, bdurel commented on components/search-result/search-result-box.tsx
> +      <AvatarGroup
LGTM

2023-01-05 19:16 UTC, lsanchezcode approved these changes
LGTM!

2023-01-05 20:18 UTC, merged