Dept 28 styling updates login logout
lsanchezcode/shoutout_frontend pull request #8
Opened 2022-11-11 20:28 UTC by blamboy090

*Please note styling has been discussed with @Kathleen updated and does not reflect on figma*
Font weight set to 500
Font type set to inter
Login/ Logout - All caps
Log out button on hover has gray box

Background does not exist on login page
DEPT heading converted into component

2022-11-11 23:13 UTC, nkhorvash requested changes
The design changes are a nice improvement. SCSS implementation is front of mind for me right now, so I made a couple small suggestions there.

2022-11-11 23:13 UTC, nkhorvash commented on components/dept-heading/dept-heading.module.scss
> +  margin-top: 3.5rem;
In our call with Brent, he recommended styling from the outer-most container in. So instead of using the margin-top on the logo to push the content down, look for what wraps all the content and style that. This also can make the code more DRY because some styling, like centering, might be achieved for multiple elements this way, instead of centering each individually.

2022-11-11 23:13 UTC, nkhorvash commented on components/dept-heading/__test__/dept-heading.test.tsx
> +});
add a new line to the end of file

2022-11-12 11:48 UTC, kathleen commented
👋 I think tagged the wrong Kathleen in your description.

2022-11-14 15:33 UTC, blamboy090 commented on components/dept-heading/__test__/dept-heading.test.tsx
> +});
added

2022-11-14 15:51 UTC, bdurel requested changes
Agree with Naysan's point about being DRY, although I don't think nesting is the answer. Also left a note about semantic tags. Otherwise looks good to me. Nice work.

2022-11-14 15:51 UTC, bdurel commented on components/dept-heading/dept-heading.tsx
> +      <h1 className={styles.keeping}>
Best practice is only one h1 for a page. You could make the subheading an h2 though.

2022-11-14 15:51 UTC, bdurel commented on components/dept-heading/dept-heading.module.scss
> +  margin-left: auto;
You could use a mixin and call it flexMargin or something like that.

2022-11-14 19:34 UTC, bdurel commented on components/dept-heading/dept-heading.module.scss
> +.headingContainer {
Given the change to add the container, you could do some sass nesting now to make the styling sheet a bit more readable. It could be this...

2022-11-14 19:35 UTC, bdurel commented on components/dept-heading/dept-heading.module.scss
> +.headingContainer {
`$color_1: #f5f5f5;
$font-family_1: Syne-Regular, Helvetica, Arial, sans-serif;

@mixin flexMargin {
  margin-left: auto;
  margin-right: auto;
}

.headingContainer {
  @include flexMargin;
  .logo {
    margin-top: 3.5em;
    display: flex;
    justify-content: center;
  }
  .title {
    @include flexMargin;
    text-align: center;
    font-family: $font-family_1;
    color: $color_1;
    font-weight: 900;
    font-size: 1.709em;
    font-style: normal;
    line-height: 145%;
    width: 17em;
    height: 2.5rem;
    margin-bottom: 0;
    margin-top: 0.563rem;
  }
  .subtitle {
    text-align: center;
    font-size: clamp(2em, 4.3vw, 3em);
    color: $color_1;
    font-weight: 300;
    margin-top: 0;
    line-height: 3.72rem;
  }
}
`

2022-11-14 19:36 UTC, bdurel commented on components/dept-heading/dept-heading.module.scss
> +.headingContainer {
okay, that looks terrible.  I'll share it in slack

2022-11-14 19:42 UTC, bdurel approved these changes

2022-11-14 20:04 UTC, nkhorvash approved these changes
LGTM

2022-11-14 21:01 UTC, merged